### ISSUE TITLE
Paths are not relative to the configuration file

### ISSUE THREAD

**Issue by ZanSara** [addisonElliott/pyqt5ac#36]
I just stumbled upon this behavior. My main script contains this line:
```python
pyqt5ac.main(config=os.path.join(os.path.dirname(os.path.realpath(__file__)), 'pyqt5ac.yml'))
```
and my `pyqt5ac.yml` is the following:
```yaml
variables:
  BASEDIR : "be_bi_pyqt_template"
ioPaths:
  -
    - "%%BASEDIR%%/resources/*.ui"
    - "%%BASEDIR%%/resources/generated/ui_%%FILENAME%%.py"
  -
    - "%%BASEDIR%%/resources/*/*.qrc"
    - "%%BASEDIR%%/resources/generated/%%FILENAME%%_rc.py"
uic_options: --from-imports
force: False
```
The two files are siblings.

When I run `main` from the same folder that contains the two files, I get:
```
Skipping example_widget, up to date
```
When I run `main` from any other folder, I get:
```
No items found in be_bi_pyqt_template/resources/*.ui
No items found in be_bi_pyqt_template/resources/*/*.qrc
```
I am looking into this issue now, as it is rather critical for me. Expect a PR soon.
